name: FLLUTER_APPLICATION_1    
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0' # Ajuste a versão do SDK conforme necessário

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/nave.png
    - assets/images/tiro.png
    - assets/images/direita.png
    - assets/images/esquerda.png
    - assets/images/espaço.png
    - assets/images/inimiga.png